version: '3.9'
services:
  # client:
  #   container_name: client
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules/
  #   ports:
  #     - 8080:8080
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    volumes:
      - ./api:/api
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
  db:
    container_name: db
    image: postgres:latest
    volumes:
    - ./db/transactions.sql:/docker-entrypoint-initdb.d/transactions.sql
    - ./db/users.sql:/docker-entrypoint-initdb.d/users.sql
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: hsaccountant
      POSTGRES_USER: hsaccountant
      POSTGRES_PASSWORD: cf%N8iX&jpGGtpM9NeSgQpHbTp7*jo2#
networks:
  default:
    name: hsaccountant