version: '3.9'
services:
  # client:
  #   container_name: client
  #   build:
  #     context: .
  #     dockerfile: ./client/docker/Dockerfile
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    volumes:
      - ./api:/api
      - /api/node_modules/
    depends_on:
      - db
    command: ["/api/docker/wait-for-it.sh", "db:5432", "--", "npm", "run", "start"]
  db:
    container_name: db
    image: postgres:latest
    volumes:
    - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: hsaccountant
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2!3#VT#E$jfxB
networks:
  adblaster:
    name: hsaccountant